version: "3"

services:
  fiber-server-1:
    image: atha02/web-server-jarkom:1.0.0
    environment:
      - PORT=8081
    expose:
      - 8081
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    command: ["go", "run", "main.go"]

  fiber-server-2:
    image: atha02/web-server-jarkom:1.0.0
    environment:
      - PORT=8081
    expose:
      - 8081
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    command: ["go", "run", "main.go"]

  fiber-server-3:
    image: atha02/web-server-jarkom:1.0.0
    environment:
      - PORT=8081
    expose:
      - 8081
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    command: ["go", "run", "main.go"]

  haproxy:
    image: haproxy:latest
    ports:
      - "8080:8080"
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - fiber-server-1
      - fiber-server-2
      - fiber-server-3
